name: Code Quality Check

on:
  pull_request:

jobs:
  call-quality-code:
    permissions:
      pull-requests: write

    name: "Check formatting and linting"
    uses: Koudmain/.github/.github/workflows/reusable-code-quality.yml@main
    with:
      node-version: "24"
